### ISSUE TITLE
Causal impact inconsistent performance

### ISSUE THREAD

**Issue by rpanai** [google/CausalImpact#15]
Running Causal Impact for the same timeserie on the same version of R (installed with the same conda environment) on two similar machines (i7-6700HQ  with ubuntu 16.10 and gcc6 , i7-7700HQ with ubuntu 16.04 and gcc5) the elapsed time is ~3.5 seconds vs ~21 seconds.  I tried to create several VM with ubuntu 17.04 and 17.10 using gcc6 and gcc7 but i couldn't get the same performance as the first machine. Do I need to install some special library on my machine to get the best from CI?

**Comment by alhauser** [comment]
I'm not aware of any configuration positively or negatively influencing the performance of CausalImpact.

What runtime did you measure on the virtual machines? Closer to the 3.5s or closer to the 21s? (It's delicate to compare runtimes on virtual machines to runtimes on real machines, though; but at least the order of magnitude would be interesting.)

Did you profile the CausalImpact calls, e.g. using `Rprof()`? This would help to understand where the bottleneck is.

**Comment by rpanai** [comment]
Hi @alhauser, I'll try to use `Rprof()` anyway the elapsed time provided by me are not on VM. I'm comparing the performance on my machine vs the one in my colleague's one.

**Comment by alhauser** [comment]
According to [this thread](https://github.com/ContinuumIO/anaconda-issues/issues/7792), it seems more related to Anaconda than to CausalImpact.
