### ISSUE TITLE
Error in bsts when using dynamic.regression

### ISSUE THREAD

**Issue by inkrement** [google/CausalImpact#18]
I tried to fit a dynamic.regression, but it seems to be broken:

```
Error in bsts(y, state.specification = ss, niter = model.args$niter, expected.model.size = 3, : Caught an exception with the following error message in MCMC iteration 63. Aborting. illegal parameter values passed to rgamma: a = 448 scale = 0

4. bsts(y, state.specification = ss, niter = model.args$niter, expected.model.size = 3, ping = 0, seed = 1, prior = sd.prior)
3. ConstructModel(data.modeling, model.args)
2. RunWithData(data, pre.period, post.period, model.args, alpha)
1. CausalImpact(serie, pre.period, post.period, model.args = list(niter = 1000, dynamic.regression = T))
```

**Comment by alhauser** [comment]
1. Does the fit of the same data set work when disabling dynamic regression?
1. Can you provide a [minimal working example](https://en.wikipedia.org/wiki/Minimal_Working_Example) that reproduces the bug?

**Comment by inkrement** [comment]
Hi Alain,

please excuse the the poor issue report from yesterday. Here is a more or less "minimal" working example, where I reduced my dataset to 2 covariates (you find a rds file in the attachment).

```R
series <- readRDS('./test_panel.rds')
pre.period <- as.Date(c("2015-09-28", "2016-05-05"))
post.period <- as.Date(c("2016-05-06", "2018-03-05"))
impact <- CausalImpact(series,pre.period , post.period, model.args = list(dynamic.regression = F)) # works
impact <- CausalImpact(series,pre.period , post.period, model.args = list(dynamic.regression = T)) # fails
```

I was able to reproduce the issue in Version 1.2.3 as well as in 1.2.4 using a rocker image and bsts 0.7.1.

**Comment by inkrement** [comment]
@alhauser Hi, I just wanna ask if you were able to reproduce the error. Maybe it is related to my system setting or some strange side effects. Anyways, I would like to use this package and it would be nice if we can resolve this issue :)

**Comment by alhauser** [comment]
Sorry for the delay!

I didn't find time to dig deeper into the problem yet, but I was able to reproduce it. However, it seems that the recent `bsts` upgrade to version 0.8.0 (provided 2 days ago) solves the problem (it now gives a warning message which we are aware of and will fix, but fitting your example works). Could you try whether updating `bsts` to the newest version also fixes the issue for you?

**Comment by alhauser** [comment]
I can confirm that updating to the newest `bsts` version fixed the issue on two different machines.

**Comment by inkrement** [comment]
@alhauser Thanks, it works now for me too!
