### ISSUE TITLE
Multiple regressors not shown in plot

### ISSUE THREAD

**Issue by pgrandinetti** [google/CausalImpact#19]
When I use CausalImpact on data like this

```
             y    x1  x2
2017-09-04   150 150 275
2017-09-05   200 249 125
2017-09-06   225 150 249
2017-09-07   150 125 275
2017-09-08   175 325 250
2017-09-09   200 175 250
```
then it seems like I get only one counterfactual prediction, even though the two time series x1 and x2 are meant to be used as indipendent. How's this single prediction computed (cfr. attachment) ?
![screenshot from 2018-05-15 13-22-26](https://user-images.githubusercontent.com/10454135/40053836-0b63e756-5843-11e8-9e38-2f256289f592.png)

**Comment by alhauser** [comment]
This works as intended: CausalImpact assumes the first column of the provided data is the response time series, and the following columns are covariates; see the description of the argument `data` in the CausalImpact help page:

```r
?CausalImpact
```

In the plot, you see the actual response `y` (black line) and the prediction for `y` (dashed blue line) with credible intervals (shaded blue area).

**Comment by steve-the-bayesian** [comment]
One point of confusion might be the roles of x1 and x2.  They get combined
(along with a time series model for y) into a single counterfactual.  You
don't get separate counterfactuals for each provided X.

**Comment by steve-the-bayesian** [comment]
They are combined using a regression with spike and slab priors, as
described in this paper:
http://people.ischool.berkeley.edu/~hal/Papers/2013/pred-present-with-bsts.pdf

Yes, there can be more than two.  The model can cope with several hundred.
Some discretion on the part of the user is helpful (i.e. don't actively
throw garbage at the tool), but the idea is to reliably and automatically
separate the "good" predictors from the "bad".

**Comment by wmelton** [comment]
@steve-the-bayesian Late to the party here. In Kay's talk, he shared a slide that looked like this: 

![image](https://user-images.githubusercontent.com/1544125/67587346-49729580-f719-11e9-9197-4c98f5d94fa5.png)

Is there an easy way to chart the Y and Predicted Y along with the covariate trends as well as shown in this screenshot from his talk?
