### ISSUE TITLE
'GammaPrior not exported by namespace: Boom' Error

### ISSUE THREAD

**Issue by geoff-lawhorn** [google/CausalImpact#21]
Hello,

I am attempting to load "CausalImpact" into my R environment and continue to get the error:
Error : object ‘GammaPrior’ is not exported by 'namespace:Boom'

Is there perhaps a package that I need to load prior to CausalImpact?

Thanks.

**Comment by steve-the-bayesian** [comment]
The Boom package exports every name that does not begin with a dot (.).
Which version of R are you using?

**Comment by geoff-lawhorn** [comment]
3.3.2

**Comment by steve-the-bayesian** [comment]
Hmmm that should work.  If you start R and load("Boom"), can you call
GammaPrior?

**Comment by geoff-lawhorn** [comment]
Hey Steve,

Looks like either updating the version or updating the packages (more likely the case in my opinion) helped.  I'm able to call gammaprior and had no issues loading the CausalImpact Package in just now.
