### ISSUE TITLE
At least as long error

### ISSUE THREAD

**Issue by ansarbutt** [google/CausalImpact#24]
Hi, 

While using my dataset for this model I've run into this error:

"bsts.model$original.series must end on a stretch of NA at least as long as y.cf"

I've tried to read the github code to better understand this error but I'm still stuck. 

Is there any advice that I can use in diagnosing this?

Thanks!

**Comment by rasnat** [comment]
Found the solution! Seems like after using 'cbind' one of my column names was the explicit reference to the column (so the column name was something like "data$field"). 

This seemed to be screwing everything up. After renaming the column the model worked.

Thanks!
