### ISSUE TITLE
Case Studies of CausalImpact

### ISSUE THREAD

**Issue by sophia-wright-blue** [google/CausalImpact#28]
thanks for releasing this amazing library! Are there any documented use cases of how Google uses this CausalImpact library on real world data?

 It'd also be helpful if someone could point me to any documentation of this library being used for practical real use cases, and not just sample data. I'm trying to understand the limitations in the interpretation of the output before I use this library to reach any conclusions for an actual use case. Thanks,

**Comment by alhauser** [comment]
Thanks for the feedback!

I'm not aware of a documentation of use cases at Google, but there are many real-world applications published in papers that cite the CausalImpact paper:

https://scholar.google.com/scholar?cites=4836725887667944732

**Comment by sophia-wright-blue** [comment]
thanks for that information @alhauser , i'll this issue open for a bit longer in case any one can point me to some other resources, thanks again

**Comment by alhauser** [comment]
Closing the thread now.

Feel free to forward to [Cross Validated](https://stats.stackexchange.com/questions/tagged/causalimpact) as it does not refer to a problem with the CausalImpact code.
