### ISSUE TITLE
Whitened innovation and other diagnostics

### ISSUE THREAD

**Issue by clamus** [google/CausalImpact#33]
I am using CausalImpact/bsts for a project and would like to use the in-sample whitened innovation (one step prediction error) to test for independence, homocedasticity, and Gaussianity, and general diagnostics.

I can find the in-sample innovation in bsts.object$one.step.prediction.errors, but after digging through the source code I cannot find the variance of the in sample innovations (This would be F_t using the notation in Durbin and Koopman 2nd ed). I assume those had to be computed somewhere to get the filtered estimates. Any pointers would be greatly appreciated.

In addition, I am also interested in testing for shocks in the state and/or observation model using the "smoothations" approach described in de Jong and Penzer (JASA 1998), which is also described at the end of Section 7.5 of Durbin and Koopman 2nd ed. These are a by-product of the disturbance smoother, which I believe bsts uses. Using the notation in Durbin and Koopman, this would be:
r_{i,t}^s = r_{i,t} / sqrt(N_{i,i,t}) and
u_{i,t}^s = u_{i,t} / sqrt(D_{i,i,t}) (in the book, there is a typo in the eq, but what I wrote here is correct).

Again, any pointers would be greatly appreciated.

Cheers!
Camilo

**Comment by steve-the-bayesian** [comment]
I think you're looking for bsts.prediction.errors(standardize=TRUE).  The
errors and the forecast variances are functions of unknowns sampled by the
MCMC, so you will get posterior draws of these quantities.
The shocks from the disturbance smoother are not exposed.

**Comment by clamus** [comment]
Thanks for the prompt response. That does the trick!
