### ISSUE TITLE
Error in value[[3L]](cond) : could not convert input data to zoo object

### ISSUE THREAD

**Issue by aminemosbah** [google/CausalImpact#40]
Error in value[[3L]](cond) : could not convert input data to zoo object
any suggestion?
thanx

**Comment by gabgilling** [comment]
I just added zoo() in front of my data like zoo(dataframe) and it fixed it for me.

**Comment by alhauser** [comment]
Assuming @gabgilling 's hint fixes the issue - thanks.

Feel free to re-open with a reproducible example if not.
