### ISSUE TITLE
Statistically Testing the post-period two series or testing the Difference equals zero

### ISSUE THREAD

**Issue by aalsharef** [google/CausalImpact#48]
Hello,

Thanks to the authors for making, sharing, and publishing this great package.  My question is: after the intervention occurs and in the post-period window, we have two-time series:
1.  The time series after the intervention (The real data)
2. The prediction time series data (Created by the library) predicting what would have happened if we didn't introduce the intervention. 

My question is: Is there a statistical test to check and test whether the difference between these two-time series is statistically significant or not.  In other words, the `plot(impact)` command would produce 3 plots (original, pointwise, and cumulative) is there a statistical test to test the hypothesis of whether the difference between the aforementioned two time series in the "pointwise" figure equals zero or not.

http://google.github.io/CausalImpact/CausalImpact.html

Thank you very much.

**Comment by alhauser** [comment]
This is exactly what the `summary()` method reports as the "Posterior prob. of a causal effect".
