### ISSUE TITLE
Adding Gformula Function to Package

### ISSUE THREAD

**Issue by resace3** [google/CausalImpact#62]
Is there any interest in adding the Gformula function to this package?

The lab I work in at Harvard developed this method as seen in [this repository ](https://github.com/CausalInference/gfoRmula) and[ this paper](https://arxiv.org/abs/1908.07072).

**Comment by kaybrodersen** [comment]
Thanks for the suggestion! Can you say more about what Gformula would help achieve in this package?

**Comment by resace3** [comment]
From quoting the CausalImpact ReadMe, " Answering a question like this can be difficult when a randomized experiment is not available. The package aims to address this difficulty using a structural Bayesian time-series model to estimate how the response metric might have evolved after the intervention if the intervention had not occurred.". 

From quoting the [Gformula paper](https://www.sciencedirect.com/science/article/pii/S2666389920300088), "When data from randomized experiments are not available, data analysts often rely on nonexperimental (observational) data to estimate causal effects. The parametric g-formula is a statistical method to estimate the causal effects of sustained treatment strategies from observational data with time-varying treatments, confounders, and outcomes. "  

Based off the purpose of CausalImpact described in the ReadMe, the Gformula as described in the Abstract of the papers seems to accomplish the goal of estimating causal effect when a "randomized experiment is unavailable".  Gformula is more commonly used in Public Health Problems as seen in the following papers:

[Intervening on risk factors for coronary heart disease: an application of the parametric g-formula](https://academic.oup.com/ije/article-abstract/38/6/1599/669228)

[The parametric g‐formula to estimate the effect of highly active antiretroviral therapy on incident AIDS or death](https://onlinelibrary.wiley.com/doi/abs/10.1002/sim.5316?casa_token=VAXpLh9KrDAAAAAA:DNyvjXIf2O5PtnHSTAF_7Duyf9QzRTEeBDsHcACd-owNEEn37hGCASaiirM_Nt-TJjk86xm6NeuqKOA)

[Occupational radon exposure and lung cancer mortality: estimating intervention effects using the parametric G formula](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4524349/)

**Comment by kaybrodersen** [comment]
I'd keep the two packages as is. In this way each package can fully focus on its approach and maintain a simple API.
