### ISSUE TITLE
missing values

### ISSUE THREAD

**Issue by markhwhiteii** [google/CausalImpact#9]
I have two models fit using this code: https://github.com/markhwhiteii/blog/blob/master/causalimpact/causalimpact.R

I'm wondering why I always get the `ggplot2` errors for missing data/data outside of the range of the plot when I run the `plot` function on an impact object:

```
Removed 82 rows containing missing values (geom_path).
Removed 164 rows containing missing values (geom_path).
```

Figures for both of the `impact` objects have straight lines for the counterfactual predictions... Does that have something to do with it? I'm not sure if I am missing something simple, but I have noticed other people run into similar problems (https://rpubs.com/heruwiryanto/Causal_impact).

**Comment by alhauser** [comment]
Fixed by pull request #29.
